---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: twcni-daemon
  namespace: kube-system
spec:
  selector:
      matchLabels:
        name: twcni-daemon
  template:
    metadata:
      labels:
        name: twcni-daemon
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: tcpwave/twcni-daemon
        name: twcni-daemon
        volumeMounts:
            - mountPath: /run/cni
              name: socket-dir
            - mountPath: /certs
              name: certs
        imagePullPolicy: Always
        args:
          - "--host=192.168.0.109"
          - "--port=7443"
          - "--username=twcadm"
          - "--password=zxcv1234"
          - "--cert=/certs/client.crt"
          - "--key=/certs/client.key"
          - "--socket-dir=/run/cni"
          - "--driver=twcni"
          - "-log_dir=/var/logs"

      volumes:
        - name: socket-dir
          hostPath:
            path: /run/cni
        - name: certs
          hostPath:
            path: /opt/tcpwave/certs
---
