---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
spec:
  containers:
  - name: nginx1
    image: nginx
  nodeSelector:
    kubernetes.io/hostname: k8s-wkr1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  containers:
  - name: nginx2
    image: nginx
  nodeSelector:
    kubernetes.io/hostname: k8s-wkr2
---
